- name: Disable nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

# CI takes care of installing dependencies
# - name: Install dependencies
#   ansible.builtin.command: npm install
#   args:
#     chdir: /app